name: Deploy to Private Server

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Reference name to simulate github.ref_name'
        required: true
        default: 'test'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Private
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.ref_name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat >>~/.ssh/config <<END
            Host host_name
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          END

      - name: Deploy Yaffa
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_REF: ${{ github.event.release.tag_name }}
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          dep: yaffa
